Ensure /var/lib/zuul is owned by zuul
Previously, the file resource did not have an
owner specfied, meaning that it defaulted to root:root.

This resulted in the following failure when starting the
zuul service:

  IOError: [Errno 13] Permission denied: '/var/lib/zuul/test'

This commit ensures propoer ownership so that zuul can start.

Change-Id: I3ee9ae49097695632114ed6692c78ebf22a08823